<?php
/**
 * Created by PhpStorm.
 * User: nata
 * Date: 16.05.17
 * Time: 20:03
 */

/**
 * Implements hook_views_pre_build().
 */
function avto_views_pre_build(&$view) {
    if (
    $view->name == 'taxonomy_term_custom' && $view->current_display == 'block_1') {
      $arg = arg(2);
      $view->field['name']->options['alter']['path'] = "products/$arg/[tid]";
    }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function avto_preprocess_page(&$vars) {
  $product_display_types = commerce_product_reference_node_types();
  if (isset($vars['node']->type) && isset($product_display_types[$vars['node']->type])) {
    $vars['title'] = $vars['node']->title;
  }
}

